Test/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'admin/index'
  get 'register/index'
  get 'login/index'
  get 'contact/index'
  get 'catalog/index'
  get 'about/index'
  get 'homepage/index'
  get 'catalog/show'
  get 'products/show'
  get 'users/new'
  #User Section
  get 'user/show',to:'users#show'
  post 'updateavatar', to: 'users#update_avatar'
  post 'update',to:'users#update_user'
  get 'deleteaccount',to:'users#delete_account'
  #Orders
  get 'buy_now', to:'orders#buy_now'
  #Contacts
  post 'contact',to:'contact#create'
  #Comments
  post 'comment', to: 'comments#create'
  #Auth errors
  get 'login_required', to: 'sessions#page_requires_login'
  get 'admin_auth_required', to: 'sessions#page_requires_admin'
  #Admin Section
  get 'admin', to: 'admin#welcome'
  post 'login_admin', to: 'sessions#login_admin'
  get 'admin/product', to:'admin#product_manage'
  get 'admin/deleteproduct', to:'admin#delete_product'
  get 'admin/user', to:'admin#user_manage'
  get 'admin/deleteuser', to:'admin#delete_user'
  get 'admin/order', to:'admin#order_manage'
  get 'admin/deleteorder', to:'admin#delete_order'
  get 'admin/contact', to:'admin#contact_manage'
  get 'admin/deletecontact', to:'admin#delete_contact'
  #Login & SignUp routes
  get 'login', to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#log_out'
  get 'authorized', to: 'sessions#page_requires_login'
  resources :products
  resources :users, only: [:new, :create]
  resources :comments


  #Index Page
  root 'homepage#index'


end

Test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Test/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/contact.rb
class Contact < ApplicationRecord
end

Test/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :users, through: :comments
  has_many :users, through: :orders
end

Test/app/models/user.rb
class User < ApplicationRecord
#  validates :fname, :lname, :email,:city,:state,:username, presence: true,
#                     length: { minimum: 2, maximum: 30}
#   validates :age,:zip, presence:true,
#                   numericality: { only_integer: true }
#   validates :email, uniqueness: true
#   validates :sex, presence:true
  has_secure_password
  has_one_attached :avatar
  has_many :comments
  has_many :orders
  has_many :products, through: :comments
  has_many :products, through: :orders

end

Test/app/controllers/about_controller.rb
class AboutController < ApplicationController
skip_before_action :authorized
  def index
  end
end

Test/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :authorized

  def product_manage
    @products = Product.all
  end

  def user_manage
    @users = User.all
  end

  def order_manage
    @orders = Order.all
  end

  def order_contact
    @orders = Contact.all
  end

  def delete_user
    @eliminate = User.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/user'
  end


  def delete_product
    @eliminate = Product.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/product'
  end

  def delete_order
    @eliminate = Order.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/order'
  end

  def delete_contact
    @eliminate = Contact.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/contact'
  end

end

Test/app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
skip_before_action :authorized
  def index
    @products = Product.all
  end
  def show
    @products = Product.all
    @selected = Product.where("category=?",params[:category])
  end
end

Test/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
      @orders = Order.all
  end

  def create
    @order = Order.create(quantity: @n_orders,user_id: params[:user_id],product_id: params[:product_id])
    @order.save
    dec_product_quantity

    redirect_back(fallback_location: root_path)
  end

  def buy_now
    @n_orders = 1
    return create
  end

  def buy_order
    @n_orders = params[:n_order]
    return create
  end

  def dec_product_quantity
    @product_bought = Product.find(params[:product_id])
    @product_bought.quantity = @product_bought.quantity - @n_orders
    @product_bought.save
  end
end

Test/app/controllers/products_controller.rb
class ProductsController < ApplicationController
skip_before_action :authorized
before_action :auth_admin, only:[:new]
  def index
    @products = Product.all
  end


  def new
  end
  def create
    @product = Product.new(params.require(:product).permit(:title,:category,:description, :price, :quantity))
    @product.save
    redirect_to @product
  end

  def show
    @product = Product.find(params[:id])
    @comments = Comment.where("product_id=?",params[:id])
  end
end

Test/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:fname,:lname,:age,:sex,:username,:email,:password,:state,:zip))
    @user.save
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def delete
    @target.destroy
  end

  def delete_account
    @target = User.find(session[:user_id])
    delete
    redirect_to '/welcome'
  end
  def update_avatar
    @user = User.find(session[:user_id])
    @user.avatar.attach(params[:avatar])
    @user.save
  end

  def update_user
    @user = User.find(session[:user_id])
    @user.update(fname: params[:fname],lname: params[:lname],age: params[:age],sex: params[:sex], username: params[:username], email: params[:email],state: params[:state], zip: params[:zip])

  end

  def show
    @user = User.find(session[:user_id])
  end
end

Test/app/helpers/about_helper.rb
module AboutHelper
end

Test/app/helpers/admin_helper.rb
module AdminHelper
end

Test/app/helpers/application_helper.rb
module ApplicationHelper
end

Test/app/helpers/catalog_helper.rb
module CatalogHelper
end

Test/app/helpers/contact_helper.rb
module ContactHelper
end

Test/app/helpers/homepage_helper.rb
module HomepageHelper
end

Test/app/helpers/login_helper.rb
module LoginHelper
end

Test/app/helpers/products_helper.rb
module ProductsHelper
end

Test/app/helpers/register_helper.rb
module RegisterHelper
end

Test/app/helpers/sessions_helper.rb
module SessionsHelper
end

Test/app/helpers/users_helper.rb
module UsersHelper
end

Test/app/views/products/new.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project DAW 1</title>

    <!-- Bootstrap core CSS -->
    <% csrf_meta_tags %>
    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <h1 class="mt-4 mb-3 text-center">
        Reserved Access Area
      </h1>

      <div class="row">
        <div class="col-lg-12 portfolio-item">
          <div class="card h-100">
            <div class="card-body">
              <h4 class="card-title text-center">
                <a href="#">Login</a>
              </h4>
              <p class="card-text ">

                <%= form_with scope: :product,url: products_path, local: true do |form| %>
                <p>
                  <%= form.label :title %><br>
                  <%= form.text_field :title, :class => "form-control col-lg-3" %>
                </p>

                <p>
                  <%= form.label :category %><br>
                  <%= form.text_field :category, :class => "form-control col-lg-3" %>
                </p>

                <p>
                  <%= form.label :description %><br>
                  <%= form.text_area :description, :class => "form-control col-lg-3" %>
                </p>

                <p>
                  <%= form.label :price %><br>
                  <%= form.text_field :price, :class => "form-control col-lg-3" %>
                </p>

                <p>
                  <%= form.label :quantity %><br>
                  <%= form.text_field :quantity, :class => "form-control col-lg-3" %>
                </p>

                <p>
                  <%= form.submit "Load new product",:class => "btn btn-primary" %>
                </p>
              <% end %>

              <!-- <form> <div class="form-group"> <label for="LoginInputEmail1">Email address</label> <input type="loginemail" class="form-control" id="LoginInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"> </div> <div class="form-group">
              <label for="LoginInputPassword1">Password</label> <input type="password" class="form-control" id="LoginInputPassword1" placeholder="Password"> </div> <div class="form-group form-check"> <input type="checkbox" class="form-check-input"
              id="KeepLoginOn"> <label class="form-check-label" for="KeepLoginOn">Keep me on</label> </div> <div class="text-center"> <button type="submit" class="btn btn-primary">Login</button> </div> </form> -->

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project DAW 1</title>
    <% csrf_meta_tags %>
    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                        <%= link_to "About", about_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                FFU
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <a class="dropdown-item" href="#">Page 1</a>
                <a class="dropdown-item" href="#">Page 2</a>
                <a class="dropdown-item" href="#">Page 3</a>
                <a class="dropdown-item" href="#">Page 4</a>
                <a class="dropdown-item" href="#">Page 5</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-fw fa-user"></i>
              </a>
              <% if logged_in? %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
                <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
              </div>
              <% else %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
                <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
              </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <h1 class="mt-4 mb-3" id="product_title"></h1>

      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <%= link_to "Home", homepage_index_path%>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "Catalog", catalog_index_path%>
        </li>
        <li class="breadcrumb-item">
          <%= link_to @product.category, catalog_show_path(:category => @product.category) %>
        </li>
        <li class="breadcrumb-item active"><%= @product.title %></li>
      </ol>

      <div class="row">

        <div class="col-lg-8">

          <%= image_tag("/images/imagecat.jpg",class: "img-fluid rounded") %>

          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <%= form_with scope: :comment,url: comments_path,local: true do |form| %>
                <div class="form-group">
                  <label>Title</label>
                  <%= text_field_tag(:title, value = nil, options = {class: 'form-control'}) %>
                  <label>Text</label>
                  <%= text_field_tag(:text, value = nil, options = {class: 'form-control'}) %>

                  </div>
                  <div class="form-group">
                </div>
                <div class="text-center">
                  <%= submit_tag "Send",:class => 'btn btn-primary'%>
                </div>
                <%end%>
            </div>
            <% @comments.each  do |comment| %>
              <h4 class="card-header">
              <% if find_author(comment.user_id).avatar.attached? %>
                <%=image_tag(find_author(comment.user_id).avatar, size: '50x50',class: "rounded-circle img-fluid")%>
              <% else %>
                <img src="//placehold.it/50"  class="rounded-circle img-fluid" alt="avatar">
              <% end %>

                    <%= find_author(comment.user_id).username %>
                  </h4>
                  <div class="card-body">
                    <h5><%= comment.title %></h5>
                      <div class="form-group">
                          <%= comment.text %>
                        </div>
                      </div>
            <% end %>

          </div>

          <div class="media mb-4">

            <div id="motherComment"></div>

          </div>

        </div>

        <div class="col-md-4">
          <div class="card my-4">
            <h5 class="card-header text-center">Buy it now!</h5>
            <div class="card-body text-center">
              <h5>
                Quantity: <a><%= @product.quantity %></a>
              </h5>
                <br>
              <h5>
                Cost: <a><%= @product.price %>$</a>
              </h5>
            </div>
            <div class="card-footer text-center">
              <%= link_to "Buy Now", {:controller => "orders", :action => "buy_now", :user_id => current_user, :product_id => @product.id}, {:class => "btn btn-primary btn-lg"}%>
            </div>
          </div>

        </div>

      </div>

    </div>
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
      </div>
    </footer>
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>

</html>