Test/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'admin/index'
  get 'register/index'
  get 'login/index'
  get 'contact/index'
  get 'catalog/index'
  get 'about/index'
  get 'homepage/index'
  get 'catalog/show'
  get 'products/show'
  get 'users/new'
  #User Section
  get 'user/show',to:'users#show'
  post 'updateavatar', to: 'users#update_avatar'
  post 'update',to:'users#update_user'
  get 'deleteaccount',to:'users#delete_account'
  #Orders
  get 'buy_now', to:'orders#buy_now'
  #Contacts
  post 'contact',to:'contact#create'
  #Comments
  post 'comment', to: 'comments#create'
  #Auth errors
  get 'login_required', to: 'sessions#page_requires_login'
  get 'admin_auth_required', to: 'sessions#page_requires_admin'
  #Admin Section
  get 'admin', to: 'admin#welcome'
  post 'login_admin', to: 'sessions#login_admin'
  get 'admin/product', to:'admin#product_manage'
  get 'admin/deleteproduct', to:'admin#delete_product'
  get 'admin/user', to:'admin#user_manage'
  get 'admin/deleteuser', to:'admin#delete_user'
  get 'admin/order', to:'admin#order_manage'
  get 'admin/deleteorder', to:'admin#delete_order'
  get 'admin/contact', to:'admin#contact_manage'
  get 'admin/deletecontact', to:'admin#delete_contact'
  #Login & SignUp routes
  get 'login', to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#log_out'
  get 'authorized', to: 'sessions#page_requires_login'
  resources :products
  resources :users, only: [:new, :create]
  resources :comments


  #Index Page
  root 'homepage#index'


end

Test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Test/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/contact.rb
class Contact < ApplicationRecord
end

Test/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :users, through: :comments
  has_many :users, through: :orders
end

Test/app/models/user.rb
class User < ApplicationRecord
#  validates :fname, :lname, :email,:city,:state,:username, presence: true,
#                     length: { minimum: 2, maximum: 30}
#   validates :age,:zip, presence:true,
#                   numericality: { only_integer: true }
#   validates :email, uniqueness: true
#   validates :sex, presence:true
  has_secure_password
  has_one_attached :avatar
  has_many :comments
  has_many :orders
  has_many :products, through: :comments
  has_many :products, through: :orders

end

Test/app/controllers/about_controller.rb
class AboutController < ApplicationController
skip_before_action :authorized
  def index
  end
end

Test/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :authorized

  def product_manage
    @products = Product.all
  end

  def user_manage
    @users = User.all
  end

  def order_manage
    @orders = Order.all
  end

  def order_contact
    @orders = Contact.all
  end

  def delete_user
    @eliminate = User.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/user'
  end


  def delete_product
    @eliminate = Product.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/product'
  end

  def delete_order
    @eliminate = Order.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/order'
  end

  def delete_contact
    @eliminate = Contact.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/contact'
  end

end

Test/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:fname,:lname,:age,:sex,:username,:email,:password,:state,:zip))
    @user.save
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def delete
    @target.destroy
  end

  def delete_account
    @target = User.find(session[:user_id])
    delete
    redirect_to '/welcome'
  end
  def update_avatar
    @user = User.find(session[:user_id])
    @user.avatar.attach(params[:avatar])
    @user.save
  end

  def update_user
    @user = User.find(session[:user_id])
    @user.update(fname: params[:fname],lname: params[:lname],age: params[:age],sex: params[:sex], username: params[:username], email: params[:email],state: params[:state], zip: params[:zip])

  end

  def show
    @user = User.find(session[:user_id])
  end
end

Test/app/helpers/about_helper.rb
module AboutHelper
end

Test/app/helpers/admin_helper.rb
module AdminHelper
end

Test/app/helpers/application_helper.rb
module ApplicationHelper
end

Test/app/helpers/catalog_helper.rb
module CatalogHelper
end

Test/app/helpers/contact_helper.rb
module ContactHelper
end

Test/app/helpers/homepage_helper.rb
module HomepageHelper
end

Test/app/helpers/login_helper.rb
module LoginHelper
end

Test/app/helpers/products_helper.rb
module ProductsHelper
end

Test/app/helpers/register_helper.rb
module RegisterHelper
end

Test/app/helpers/sessions_helper.rb
module SessionsHelper
end

Test/app/helpers/users_helper.rb
module UsersHelper
end

Test/app/views/admin/contact_manage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Admin Section", admin_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Product", admin_product_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "User", admin_user_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Order", admin_order_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", admin_contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
      Reserved Area Access
    </h1>

    <div class="row">
      <div class="col-lg-12 portfolio-item">
        <div class="card h-100">
          <div class="card-body">
            <p class="card-text">
              <table class='table'>
                <tr>
                  <th>ID</th>
                  <th>Author</th>
                  <th>Telnumb</th>
                  <th>Email</th>
                  <th>Text</th>
                  <th>Services</th>
                </tr>
                <% if !@contacts.nil? %>
                <% @contacts.each  do |contact| %>
                <tr>
                  <th><%= contact.id %></th>
                  <th><%= contact.name %></th>
                  <th><%= contact.telnumb %></th>
                  <th><%= contact.email %></th>
                  <th><%= contact.msg %></th>
                  <th><%= link_to "Delete", admin_deletecontact_path(:id => contact.id)%></th>
                </tr>
                <% end %>
                <%end%>
            </p>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->



  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/admin/order_manage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Admin Section", admin_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Product", admin_product_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "User", admin_user_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Order", admin_order_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", admin_contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
      Reserved Area Access
    </h1>

    <div class="row">
      <div class="col-lg-12 portfolio-item">
        <div class="card h-100">
          <div class="card-body">
            <p class="card-text">
              <table class='table'>
                <tr>
                  <th>ID</th>
                  <th>Buyer's Username</th>
                  <th>Product Bought</th>
                  <th>Cost</th>
                  <th>Service</th>
                </tr>
                <% if !@orders.nil? %>
                <% @orders.each  do |order| %>
                <tr>
                  <th><%= order.id %></th>
                  <th><%= find_author(order.user_id).username %></th>
                  <th><%= find_product(order.product_id).title %></th>
                  <th><%= find_product(order.product_id).price %></th>
                  <th><%= link_to "Delete", admin_deleteorder_path(:id => order.id)%></th>
                </tr>
                <% end %>
                <% end %>
            </p>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->



  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/admin/product_manage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Admin Section", admin_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Product", admin_product_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "User", admin_user_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Order", admin_order_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", admin_contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
      Reserved Area Access
    </h1>

    <div class="row">
      <div class="col-lg-12 portfolio-item">
        <div class="card h-100">
          <div class="card-body">
            <p class="card-text">
              <table class='table'>
                <tr>
                  <th>ID</th>
                  <th>Product's name</th>
                  <th>Price</th>
                  <th>Quantity</th>
                  <th>Services</th>
                </tr>
                <% if !@products.nil? %>
                <% @products.each  do |product| %>
                <tr>
                  <th><%= product.id %></th>
                  <th><%= product.title %></th>
                  <th><%= product.price%></th>
                  <th><%= product.quantity%></th>
                  <th><%= link_to "Delete", admin_deleteproduct_path(:id => product.id)%></th>
                </tr>
                <% end %>
                <%end%>
            </p>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->



  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/admin/user_manage.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Admin Section", admin_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Product", admin_product_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "User", admin_user_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Order", admin_order_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
      Reserved Area Access
    </h1>

    <div class="row">
      <div class="col-lg-12 portfolio-item">
        <div class="card h-100">
          <div class="card-body">
            <p class="card-text">
              <table class='table'>
                <tr>
                  <th>ID</th>
                  <th>Username</th>
                  <th>First name</th>
                  <th>Last name</th>
                  <th>Age</th>
                  <th>email</th>
                  <th>Services</th>
                </tr>
                <% @users.each  do |user| %>
                <tr>
                  <th><%= user.id %></th>
                  <th><%= user.username %></th>
                  <th><%= user.fname %></th>
                  <th><%= user.lname %></th>
                  <th><%= user.age %></th>
                  <th><%= user.email %></th>
                  <th><%= link_to "Delete", admin_deleteuser_path(:id => user.id)%></th>
                </tr>
                <% end %>
            </p>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->



  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/admin/welcome.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Admin Section", admin_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Product", admin_product_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "User", admin_user_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Order", admin_order_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", admin_contact_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">
      Reserved Area Access
    </h1>

    <div class="row">
      <div class="col-lg-12 portfolio-item">
        <div class="card h-100">
          <div class="card-body">
            <p class="card-text">
              <% if logged_in? && is_admin? %>
                <div class="text-center">
                  <h3>Welcome back <%= current_user.username %>!</h3>
                </div>
              <% elsif logged_in? && !is_admin? %>
              <script type="text/javascript">
                  window.location.href="/admin_auth_required"
              </script>
              <%else%>
              <%end%>

          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntegrateProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>