Test/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'admin/index'
  get 'register/index'
  get 'login/index'
  get 'contact/index'
  get 'catalog/index'
  get 'about/index'
  get 'homepage/index'
  get 'catalog/show'
  get 'products/show'
  get 'users/new'
  #User Section
  get 'user/show',to:'users#show'
  post 'updateavatar', to: 'users#update_avatar'
  post 'update',to:'users#update_user'
  get 'deleteaccount',to:'users#delete_account'
  #Orders
  get 'buy_now', to:'orders#buy_now'
  #Contacts
  post 'contact',to:'contact#create'
  #Comments
  post 'comment', to: 'comments#create'
  #Auth errors
  get 'login_required', to: 'sessions#page_requires_login'
  get 'admin_auth_required', to: 'sessions#page_requires_admin'
  #Admin Section
  get 'admin', to: 'admin#welcome'
  post 'login_admin', to: 'sessions#login_admin'
  get 'admin/product', to:'admin#product_manage'
  get 'admin/deleteproduct', to:'admin#delete_product'
  get 'admin/user', to:'admin#user_manage'
  get 'admin/deleteuser', to:'admin#delete_user'
  get 'admin/order', to:'admin#order_manage'
  get 'admin/deleteorder', to:'admin#delete_order'
  get 'admin/contact', to:'admin#contact_manage'
  get 'admin/deletecontact', to:'admin#delete_contact'
  #Login & SignUp routes
  get 'login', to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#log_out'
  get 'authorized', to: 'sessions#page_requires_login'
  resources :products
  resources :users, only: [:new, :create]
  resources :comments


  #Index Page
  root 'homepage#index'


end

Test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Test/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/contact.rb
class Contact < ApplicationRecord
end

Test/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :users, through: :comments
  has_many :users, through: :orders
end

Test/app/models/user.rb
class User < ApplicationRecord
#  validates :fname, :lname, :email,:city,:state,:username, presence: true,
#                     length: { minimum: 2, maximum: 30}
#   validates :age,:zip, presence:true,
#                   numericality: { only_integer: true }
#   validates :email, uniqueness: true
#   validates :sex, presence:true
  has_secure_password
  has_one_attached :avatar
  has_many :comments
  has_many :orders
  has_many :products, through: :comments
  has_many :products, through: :orders

end

Test/app/controllers/about_controller.rb
class AboutController < ApplicationController
skip_before_action :authorized
  def index
  end
end

Test/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :authorized

  def product_manage
    @products = Product.all
  end

  def user_manage
    @users = User.all
  end

  def order_manage
    @orders = Order.all
  end

  def order_contact
    @orders = Contact.all
  end

  def delete_user
    @eliminate = User.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/user'
  end


  def delete_product
    @eliminate = Product.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/product'
  end

  def delete_order
    @eliminate = Order.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/order'
  end

  def delete_contact
    @eliminate = Contact.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/contact'
  end

end

Test/app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
skip_before_action :authorized
  def index
    @products = Product.all
  end
  def show
    @products = Product.all
    @selected = Product.where("category=?",params[:category])
  end
end

Test/app/controllers/contact_controller.rb
class ContactController < ApplicationController
skip_before_action :authorized
  def index
  end

  def create
    @contact = Contact.create(params.require(:contact).permit(:name,:telnumb,:email,:msg))
    @contact.save
  end
end

Test/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
      @orders = Order.all
  end

  def create
    @order = Order.create(quantity: @n_orders,user_id: params[:user_id],product_id: params[:product_id])
    @order.save
    dec_product_quantity

    redirect_back(fallback_location: root_path)
  end

  def buy_now
    @n_orders = 1
    return create
  end

  def buy_order
    @n_orders = params[:n_order]
    return create
  end

  def dec_product_quantity
    @product_bought = Product.find(params[:product_id])
    @product_bought.quantity = @product_bought.quantity - @n_orders
    @product_bought.save
  end
end

Test/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:fname,:lname,:age,:sex,:username,:email,:password,:state,:zip))
    @user.save
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def delete
    @target.destroy
  end

  def delete_account
    @target = User.find(session[:user_id])
    delete
    redirect_to '/welcome'
  end
  def update_avatar
    @user = User.find(session[:user_id])
    @user.avatar.attach(params[:avatar])
    @user.save
  end

  def update_user
    @user = User.find(session[:user_id])
    @user.update(fname: params[:fname],lname: params[:lname],age: params[:age],sex: params[:sex], username: params[:username], email: params[:email],state: params[:state], zip: params[:zip])

  end

  def show
    @user = User.find(session[:user_id])
  end
end

Test/app/helpers/about_helper.rb
module AboutHelper
end

Test/app/helpers/admin_helper.rb
module AdminHelper
end

Test/app/helpers/application_helper.rb
module ApplicationHelper
end

Test/app/helpers/catalog_helper.rb
module CatalogHelper
end

Test/app/helpers/contact_helper.rb
module ContactHelper
end

Test/app/helpers/homepage_helper.rb
module HomepageHelper
end

Test/app/helpers/login_helper.rb
module LoginHelper
end

Test/app/helpers/products_helper.rb
module ProductsHelper
end

Test/app/helpers/register_helper.rb
module RegisterHelper
end

Test/app/helpers/sessions_helper.rb
module SessionsHelper
end

Test/app/helpers/users_helper.rb
module UsersHelper
end

Test/app/views/contact/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>
  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
                      <%= link_to "About", about_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <% if logged_in? %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
              <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
            </div>
            <% else %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
              <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
            </div>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Contact
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", homepage_index_path%>
      </li>
      <li class="breadcrumb-item active">Contact</li>
    </ol>

    <!-- Content Row -->
    <div class="row">
      <!-- Map Column -->
      <div class="col-lg-8 mb-4">
        <!-- Embedded Google Map -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3520.407866412093!2d-15.453664984929935!3d28.073099182641897!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xc4095d45a6f90ef%3A0xdc47519abbbe0084!2sEscuela%20De%20Ingenier%C3%ADa%20inform%C3%A1tica!5e0!3m2!1sen!2ses!4v1571093670881!5m2!1sen!2ses" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
      </div>
      <!-- Contact Details Column -->
      <div class="col-lg-4 mb-4">
        <h3>Bassano's Reality Group</h3>
        <p>
          35017 Las Palmas
          <br>Las Palmas de Gran Canaria
          <br>
        </p>
        <p>
          <i class="fa fa-envelope" aria-hidden="true"></i>
          <a href="mailto:bassano@notarealemail.com">: bassano@notarealemail.com
          </a>
        </p>
        <p>
        <i class="fa fa-clock-o" aria-hidden="true"></i> : Monday - Friday: 9:00 AM to 5:00 PM
        </p>
      </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Send us a Message</h3>
        <%= form_with scope: :contact ,url: contact_path, local: true do |form| %>
          <div class="control-group form-group">
            <div class="controls">
              <label>Full Name:</label>
              <%= form.text_field :name, class: 'form-control'%>
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Phone Number:</label>
              <%= form.text_field :telnumb, class: 'form-control'%>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Email Address:</label>
              <%= form.text_field :email, class: 'form-control'%>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Message:</label>
              <%= form.text_area :msg, class: 'form-control'%>
            </div>
          </div>
          <div id="success"></div>
          <%= form.submit 'Send Message', :class => 'btn btn-primary' %>
        <% end %>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Bassano</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Contact form JavaScript -->
  <!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
  <script src="js/jqBootstrapValidation.js"></script>
  <script src="js/contact_me.js"></script>

</body>

</html>

Test/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/modern-business.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
                      <%= link_to "About", about_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", login_index_path, :class => "dropdown-item"%>
              <%= link_to "Register", register_index_path, :class => "dropdown-item"%>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container py-4">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Portfolio 1
      <small>Subheading</small>
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active">Portfolio 1</li>
    </ol>


    <div class="row">
      <div class="col-md-12">
        <div class="text-center">
        <h3 class="">Insert your data</h3>
        </div>
        <%= form_with scope: :user,url: users_path, local: true do |form| %>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label>First name</label>
              <%= form.text_field :fname, class: 'form-control'%>

            </div>
            <div class="col-md-6 mb-3">
              <label for="validationDefault02">Last name</label>
              <%= form.text_field :lname, class: 'form-control'%>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="validationAge">Age</label>
              <%= form.text_field :age, class: 'form-control'%>
            </div>
            <div class="col-md-6 mb-3">
              <label for="validationSex">Sex</label>
              <br>
              <%= form.label :sex, "Male", :value => "male"  %>
              <%= form.radio_button :sex, "male" %>
              <%= form.label :sex, "Female", :value => "female" %>
              <%= form.radio_button :sex, "female" %>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="validationDefaultUsername">Username</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend2">@</span>
                </div>
                <%= form.text_field :username, class: 'form-control'%>
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="validationDefaultUsername">Email</label>
              <div class="input-group">
                <%= form.text_field :email, class: 'form-control'%>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6 mb-3">
              <label for="validationDefault03">Password</label>
              <%= form.text_field :password, class: 'form-control'%>
            </div>
            <div class="col-md-3 mb-3">
              <label for="validationDefault04">State</label>
              <%= form.text_field :state, class: 'form-control'%>
            </div>
            <div class="col-md-3 mb-3">
              <label for="validationDefault05">Zip</label>
              <%= form.text_field :zip, class: 'form-control'%>
            </div>
          </div>
          <div class="form-group">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required>
              <label class="form-check-label" for="invalidCheck2">
                Agree to terms and conditions
              </label>
            </div>
          </div>
          <%= form.submit 'Create New Account', :class => 'btn btn-primary' %>
        <% end %>
        <%= flash[:notice] %>
      </div>
    </div>
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
                      <%= link_to "About", about_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <% if logged_in? %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
              <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
            </div>
            <% else %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
              <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
            </div>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row my-2">
        <div class="col-lg-8 order-lg-2">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Messages(still working on...)</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#edit" data-toggle="tab" class="nav-link">Edit</a>
                </li>
            </ul>
            <div class="tab-content py-4">
                <div class="tab-pane active" id="profile">
                    <h5 class="mb-3">User Profile</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <h6>About</h6>
                            <p>
                                Still working on..
                            </p>
                            <h6>Hobbies</h6>
                            <p>
                                Still working on..
                            </p>
                        </div>
                        <div class="col-md-12">
                            <h5 class="mt-2"><%= link_to "Delete Account", deleteaccount_path, :class => "btn btn-danger"%></h5>
                        </div>
                    </div>
                    <!--/row-->
                </div>
                <div class="tab-pane" id="messages">
                    <div class="alert alert-info alert-dismissable">
                        <a class="panel-close close" data-dismiss="alert">×</a> This is an <strong>.alert</strong>. Use this to show important messages to the user.
                    </div>
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <td>
                                   <span class="float-right font-weight-bold">3 hrs ago</span> Here is your a link to the latest summary report from the..
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   <span class="float-right font-weight-bold">Yesterday</span> There has been a request on your account since that was..
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   <span class="float-right font-weight-bold">9/10</span> Porttitor vitae ultrices quis, dapibus id dolor. Morbi venenatis lacinia rhoncus.
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   <span class="float-right font-weight-bold">9/4</span> Vestibulum tincidunt ullamcorper eros eget luctus.
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   <span class="float-right font-weight-bold">9/4</span> Maxamillion ais the fix for tibulum tincidunt ullamcorper eros.
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane" id="edit">
                    <%= form_with(url: "/update", method: "post") do |form| %>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">First name</label>
                            <div class="col-lg-9">
                                <%= form.text_field :fname, class: 'form-control',value:current_user.fname%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Last name</label>
                            <div class="col-lg-9">
                                <%= form.text_field :lname, class: 'form-control',value:current_user.lname%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Age</label>
                            <div class="col-lg-9">
                                <%= form.text_field :age, class: 'form-control',value:current_user.age %>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Sex</label>
                            <div class="col-lg-9">
                                <%= form.text_field :sex, class: 'form-control',value:current_user.sex%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Username</label>
                            <div class="col-lg-9">
                                <%= form.text_field :username, class: 'form-control',value:current_user.username%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Email</label>
                            <div class="col-lg-9">
                                <%= form.text_field :email, class: 'form-control',value:current_user.email%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">State</label>
                            <div class="col-lg-9">
                                <%= form.text_field :state, class: 'form-control',value:current_user.state%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Zip</label>
                            <div class="col-lg-9">
                                <%= form.text_field :zip, class: 'form-control',value:current_user.zip%>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label"></label>
                            <div class="col-lg-9">
                                <input type="reset" class="btn btn-secondary" value="Cancel">
                                <%= submit_tag 'Save Changes', class: 'btn btn-primary'%>
                            </div>
                        </div>
                    <%end%>
                </div>
            </div>
        </div>
        <div class="col-lg-4 order-lg-1 text-center">
            <%= form_with(url: "/updateavatar", method: "post") do |form| %>
              <% if @user.avatar.attached? %>
                <%=image_tag(current_user.avatar, size: '150x150',class: "rounded-circle")%>
              <% else %>
                <img src="//placehold.it/150"   class="rounded-circle" alt="avatar">
              <% end %>
              <h6 class="mt-2">Upload a different photo</h6>
              <%= form.file_field :avatar %>
              <%= form.submit 'Upload', :class => 'btn btn-primary' %>
            <% end %>
        </div>
    </div>
</div>

</body>

</html>