Test/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'admin/index'
  get 'register/index'
  get 'login/index'
  get 'contact/index'
  get 'catalog/index'
  get 'about/index'
  get 'homepage/index'
  get 'catalog/show'
  get 'products/show'
  get 'users/new'
  #User Section
  get 'user/show',to:'users#show'
  post 'updateavatar', to: 'users#update_avatar'
  post 'update',to:'users#update_user'
  get 'deleteaccount',to:'users#delete_account'
  #Orders
  get 'buy_now', to:'orders#buy_now'
  #Contacts
  post 'contact',to:'contact#create'
  #Comments
  post 'comment', to: 'comments#create'
  #Auth errors
  get 'login_required', to: 'sessions#page_requires_login'
  get 'admin_auth_required', to: 'sessions#page_requires_admin'
  #Admin Section
  get 'admin', to: 'admin#welcome'
  post 'login_admin', to: 'sessions#login_admin'
  get 'admin/product', to:'admin#product_manage'
  get 'admin/deleteproduct', to:'admin#delete_product'
  get 'admin/user', to:'admin#user_manage'
  get 'admin/deleteuser', to:'admin#delete_user'
  get 'admin/order', to:'admin#order_manage'
  get 'admin/deleteorder', to:'admin#delete_order'
  get 'admin/contact', to:'admin#contact_manage'
  get 'admin/deletecontact', to:'admin#delete_contact'
  #Login & SignUp routes
  get 'login', to: 'sessions#new'
  post 'login_user', to: 'sessions#login_user'
  get 'welcome', to: 'sessions#welcome'
  get 'logout', to: 'sessions#log_out'
  get 'authorized', to: 'sessions#page_requires_login'
  resources :products
  resources :users, only: [:new, :create]
  resources :comments


  #Index Page
  root 'homepage#index'


end

Test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Test/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/contact.rb
class Contact < ApplicationRecord
end

Test/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user 
end

Test/app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :users, through: :comments
  has_many :users, through: :orders
end

Test/app/models/user.rb
class User < ApplicationRecord
#  validates :fname, :lname, :email,:city,:state,:username, presence: true,
#                     length: { minimum: 2, maximum: 30}
#   validates :age,:zip, presence:true,
#                   numericality: { only_integer: true }
#   validates :email, uniqueness: true
#   validates :sex, presence:true
  has_secure_password
  has_one_attached :avatar
  has_many :comments
  has_many :orders
  has_many :products, through: :comments
  has_many :products, through: :orders

end

Test/app/controllers/about_controller.rb
class AboutController < ApplicationController
skip_before_action :authorized
  def index
  end
end

Test/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :authorized

  def product_manage
    @products = Product.all
  end

  def user_manage
    @users = User.all
  end

  def order_manage
    @orders = Order.all
  end

  def order_contact
    @orders = Contact.all
  end

  def delete_user
    @eliminate = User.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/user'
  end


  def delete_product
    @eliminate = Product.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/product'
  end

  def delete_order
    @eliminate = Order.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/order'
  end

  def delete_contact
    @eliminate = Contact.find(params[:id])
    @eliminate.destroy
    redirect_to '/admin/contact'
  end

end

Test/app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
skip_before_action :authorized
  def index
    @products = Product.all
  end
  def show
    @products = Product.all
    @selected = Product.where("category=?",params[:category])
  end
end

Test/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
      @orders = Order.all
  end

  def create
    @order = Order.create(quantity: @n_orders,user_id: params[:user_id],product_id: params[:product_id])
    @order.save
    dec_product_quantity

    redirect_back(fallback_location: root_path)
  end

  def buy_now
    @n_orders = 1
    return create
  end

  def buy_order
    @n_orders = params[:n_order]
    return create
  end

  def dec_product_quantity
    @product_bought = Product.find(params[:product_id])
    @product_bought.quantity = @product_bought.quantity - @n_orders
    @product_bought.save
  end
end

Test/app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :show]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:fname,:lname,:age,:sex,:username,:email,:password,:state,:zip))
    @user.save
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def delete
    @target.destroy
  end

  def delete_account
    @target = User.find(session[:user_id])
    delete
    redirect_to '/welcome'
  end
  def update_avatar
    @user = User.find(session[:user_id])
    @user.avatar.attach(params[:avatar])
    @user.save
  end

  def update_user
    @user = User.find(session[:user_id])
    @user.update(fname: params[:fname],lname: params[:lname],age: params[:age],sex: params[:sex], username: params[:username], email: params[:email],state: params[:state], zip: params[:zip])

  end

  def show
    @user = User.find(session[:user_id])
  end
end

Test/app/helpers/about_helper.rb
module AboutHelper
end

Test/app/helpers/admin_helper.rb
module AdminHelper
end

Test/app/helpers/application_helper.rb
module ApplicationHelper
end

Test/app/helpers/catalog_helper.rb
module CatalogHelper
end

Test/app/helpers/contact_helper.rb
module ContactHelper
end

Test/app/helpers/homepage_helper.rb
module HomepageHelper
end

Test/app/helpers/login_helper.rb
module LoginHelper
end

Test/app/helpers/products_helper.rb
module ProductsHelper
end

Test/app/helpers/register_helper.rb
module RegisterHelper
end

Test/app/helpers/sessions_helper.rb
module SessionsHelper
end

Test/app/helpers/users_helper.rb
module UsersHelper
end

Test/app/views/about/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>
  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

  <body>

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                        <%= link_to "About", about_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                FFU
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <a class="dropdown-item" href="#">Page 1</a>
                <a class="dropdown-item" href="#">Page 2</a>
                <a class="dropdown-item" href="#">Page 3</a>
                <a class="dropdown-item" href="#">Page 4</a>
                <a class="dropdown-item" href="#">Page 5</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-fw fa-user"></i>
              </a>
              <% if logged_in? %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
                <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
              </div>
              <% else %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
                <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
              </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <h1 class="mt-4 mb-3">About
        <small>Bassano Group</small>
      </h1>

      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <%= link_to "Home", homepage_index_path%>
        </li>
        <li class="breadcrumb-item active">About</li>
      </ol>

      <!-- Intro Content -->
      <div class="row">
        <div class="col-lg-6">
          <img class="img-fluid rounded mb-4" src="/images/users.jpg" alt="">
        </div>
        <div class="col-lg-6">
          <h2>Who we are?</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
        </div>
      </div>
      <!-- /.row -->

      <!-- Team Members -->
      <h2>Our Team</h2>

      <div class="row">
        <div class="col-lg-3 mb-3">
          <div class="card h-100 text-center">
            <img class="card-img-top" src="/images/crazyhat.jfif" alt="">
            <div class="card-body">
              <h4 class="card-title">Ludovico Ghergo</h4>
              <h6 class="card-subtitle mb-2 text-muted">Developer</h6>
              <p class="card-text">Simply the best.<br>
                Also know as the only one who codes.
              </p>
            </div>
            <div class="card-footer">
              <a href="#">
                <i class="fa fa-envelope" aria-hidden="true"></i>
              </a>
              <a href="#">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="#">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-lg-3 mb-3">
          <div class="card h-100 text-center">
            <img class="card-img-top" src="/images/user-male-icon.png" alt="">
            <div class="card-body">
              <h4 class="card-title">Giacomo</h4>
              <h6 class="card-subtitle mb-2 text-muted">Developer</h6>
              <p class="card-text"></div>
              <div class="card-footer">
                <a href="#">name@example.com</a>
              </div>
            </div>
          </div>
          <div class="col-lg-3 mb-3">
            <div class="card h-100 text-center">
              <img class="card-img-top" src="/images/user-male-icon.png" alt="">
              <div class="card-body">
                <h4 class="card-title">Rafael</h4>
                <h6 class="card-subtitle mb-2 text-muted">Developer</h6>
                <p class="card-text"></div>
                <div class="card-footer">
                  <a href="#">name@example.com</a>
                </div>
              </div>
            </div>
            <div class="col-lg-3 mb-3">
              <div class="card h-100 text-center">
                <img class="card-img-top" src="/images/user-male-icon.png" alt="">
                <div class="card-body">
                  <h4 class="card-title">Andrea</h4>
                  <h6 class="card-subtitle mb-2 text-muted">Developer</h6>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus aut mollitia eum ipsum fugiat odio officiis odit.</p>
                </div>
                <div class="card-footer">
                  <a href="#">name@example.com</a>
                </div>
              </div>
            </div>
          </div>
          <!-- /.row -->

          <!-- Our Customers -->
          <h2>Our Collaborators</h2>
          <div class="row">
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
            <div class="col-lg-2 col-sm-4 mb-4">
              <img class="img-fluid" src="/images/collaborators.png" alt="">
            </div>
          </div>
          <!-- /.row -->

        </div>
        <!-- /.container -->

        <!-- Footer -->
        <footer class="py-5 bg-dark">
          <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

      </body>

    </html>

Test/app/views/catalog/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project DAW 1</title>

  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
                      <%= link_to "About", about_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <% if logged_in? %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
              <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
            </div>
            <% else %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
              <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
            </div>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Catalog</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active">Catalog</li>
    </ol>
    <div class="row">
      <% @products.select("DISTINCT(CATEGORY)").each  do |product| %>
      <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="catalog_desktop.html"><%= image_tag("/images/imagecat.jpg", class: "card-img-top") %></a>
          <div class="card-body">
            <h4 class="card-title">
              <%=link_to product.category,catalog_show_path(:category => product.category) %>
            </h4>
            <p class="card-text"></div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

Test/app/views/catalog/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Project Daw1</title>

  <!-- Bootstrap core CSS -->
  <% csrf_meta_tags %>
  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "modern-business ", media: "all", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag    "application", 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <%= link_to "Bassano", root_path, :class => "navbar-brand"%>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
                      <%= link_to "About", about_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Catalog", catalog_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, :class => "nav-link"%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              FFU
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <a class="dropdown-item" href="#">Page 1</a>
              <a class="dropdown-item" href="#">Page 2</a>
              <a class="dropdown-item" href="#">Page 3</a>
              <a class="dropdown-item" href="#">Page 4</a>
              <a class="dropdown-item" href="#">Page 5</a>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-user"></i>
            </a>
            <% if logged_in? %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Your Account", user_show_path, :class => "dropdown-item"%>
              <%= link_to "Log Out", logout_path, :class => "dropdown-item"%>
            </div>
            <% else %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
              <%= link_to "Login", sessions_welcome_path, :class => "dropdown-item"%>
              <%= link_to "Register", sessions_new_path, :class => "dropdown-item"%>
            </div>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Catalog
      <small><%=params[:category]%></small>
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", homepage_index_path%>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Catalog", catalog_index_path%>
      </li>
      <li class="breadcrumb-item active">
        <%= link_to params[:category], catalog_show_path(:category => params[:category])%>
      </li>
    </ol>

    <!-- Content Row -->
    <div class="row">

      <div class="col-lg-2" height="100">
        <ul class="list-group">
          <div class="mb-4" id="accordion" role="tablist" aria-multiselectable="true">
              <% @products.select("DISTINCT(CATEGORY)").each  do |product| %>
              <li class="list-group-item list-group-item-action">
                <%= link_to product.category,catalog_show_path(:category => product.category),{'data-toggle' => "collapse",'data-parent' =>"#accordion",'aria-expanded' => "true",'aria-controls'=>"collapseOne"} %>
                <% if product.category == params[:category] %>
                  <div id="DesktopNavSide" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
                <% else %>
                  <div id="DesktopNavSide" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                <% end %>
                  <div class="card-body">

                    <a href="#">Section 1</a><br>
                    <a href="#">Section 2</a><br>
                    <a href="#">Section 3</a><br>
                    <a href="#">Section 4</a><br>

                  </div>
                </div>
              </li>
              <% end %>
          </div>
        </ul>
      </div>


    <div class="container d-block col-lg-10">
        <div class="row w-100">
            <% @selected.each  do |product| %>
              <div class="col-lg-3 col-sm-6 portfolio-item">
                <div class="card h-100">
                  <a><%= image_tag("/images/imagecat.jpg",class: "card-img-top") %></a>
                  <div class="card-body">
                    <h4 class="card-title">
                      <%= link_to product.title,products_show_path(:id => product.id) %>
                    </h4>
                    <p class="card-text" id="article_catalog_desc_0"></p>
                  </div>
                  <div class="card-footer">
                    <%= link_to "Learn More",products_show_path(:id => product.id),class:"btn btn-primary" %>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
    </div>
   </div>
</div>

  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
  </footer>

  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>

</html>